server:
  port: 8888
eureka:
  instance:
    hostname: localhost:8761 
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/